
const navbarToggle = document.querySelector('.navbar-toggle');
const navbarMenu = document.querySelector('.navbar-menu');

navbarToggle.addEventListener('click', () => {
    navbarToggle.classList.toggle('active');
    navbarMenu.classList.toggle('active');
});
document.getElementById("scrollTopBtn").addEventListener("click", () =>
  window.scrollTo({ top: 0, behavior: "smooth" })
);

//tranlating the page:

const translations = {
  en: {
    startseite: 'Home',
    ueberUns: 'About Us',
    galerie: 'Gallery',
    leistungen: 'Services',
    headline: 'Precision is our drive\nTrust is our strength',
    mainQuestion: 'What is KINZEL TRANSPORTE.DE?',
    mainDescription: 'KINZEL TRANSPORTE is a growing transport company based in Elmshorn. Our fleet currently includes 25 container chassis trucks and is located near the Port of Hamburg. Founded in 2019 by Mr. Kinzel, the company quickly developed into a high-performance provider of transport and logistics services, thanks to our committed team. Our fleet allows us maximum flexibility and individualized responses to customer needs. Whether time pressure, just-in-time delivery, or temporary storage—our priority is fulfilling customer expectations.',
    fleetTitle: 'Meet the Fleet: Kinzel on the Road',
    portTitle: 'The Driving Force of the Port of Hamburg',
    portText: 'Thanks to its strategic location near the Port of Hamburg, Kinzel Transporte operates at the heart of German logistics. Our trucks serve numerous terminals and container depots daily, ensuring smooth and fast cargo movement. We cooperate closely with local operators, port authorities, and international clients to guarantee efficient and punctual deliveries. With regional expertise and trusted partnerships, Kinzel is a preferred partner for container transport in and around Hamburg.',
    locationTitle: 'Here’s Where You’ll Find Us',
    locationDescription: 'We offer sea container transport. Our main operation areas are the ports of Hamburg and Bremen. Our driver routes cover the whole northern region of Germany. Larger delivery routes are possible upon request.',
    advert1: '✓ Perfect Deliveries',
    advert2: '✓ On-time Deliveries',
    advert3: '✓ Reliable Groupage Transport',
    advert4: '✓ Cargo Security',
    workTitle: 'What Kind of Work Environment We Offer',
    workDescription: 'We provide the following activities shown in the photos below: modern equipment, organized logistics, and a stable work environment where every detail matters.',
    image1: 'Heavy-Duty Trucks',
    image2: 'Teamwork',
    image3: 'Scale and Precision',
    copyright: '© 2025 Kinzel Transporte.de. All rights reserved.',
    headlinefirst: 'Precision is our driving force Trust is our strength',
    headlineDescription: 'KINZEL TRANSPORTE.DE offers reliable and secure container transport with a modern fleet and proven service.',
    whatIsK: 'What is KINZEL TRANSPORTE.DE?',
    whatIsKDes: 'KINZEL TRANSPORTE is a growing transport company based in Elmshorn. Our fleet currently consists of 25 container chassis tractors and is located near the Port of Hamburg. Kinzel Transporte was founded by Mr. Kinzel in Elmshorn in 2019 and, thanks to our dedicated employees, has quickly developed into a powerful provider of transport and logistics services. Our fleet allows us maximum flexibility and the ability to respond individually to specific customer requirements. Whether its tight deadlines, just-in-time delivery, or interim storage of your goods – we do everything we can to meet our customers needs.',
    onMove: 'Meet the fleet: Kinzel on the move',
    nextToVideo: 'The driving force of the Port of Hamburg',
    NextToVideoPar: 'Thanks to its strategic location in close proximity to the Port of Hamburg, Kinzel Transporte operates at the heart of German logistics. Our tugboats serve numerous terminals and container depots daily, ensuring smooth and rapid cargo transfer from port to port. We work closely with local operators, port authorities, and international customers to ensure that every shipment reaches its destination efficiently and on time. Thanks to our regional expertise and established partnerships, Kinzel Transporte has established itself as a reliable and preferred partner for container transport in Hamburg and the surrounding area.',
    locationTitle: 'You can find us here', 
    locationTitleP: 'We offer sea container transport. Our main operating area is the ports of Hamburg and Bremen. Our chauffeur-driven tours extend beyond these areas and cover the entire northern German region. Longer tours are available upon request.',
    first: 'Impeccable deliveries',
    second: 'On-time deliveries',
    third: 'Reliable groupage transport',
    fourth: 'Load securing',
    highlighthtwo: 'What kind of working environment we have:',
    highlighthtwoP:'We offer the following activities, which you can see in the photos below: modern equipment, organized logistics, and a stable work environment where every detail matters.',
    truck1text:'Big Trucks',
    truck2text:'Team work',
    truck3text:'Scale and precision',
    lione: 'HOME PAGE',
    litwo: 'ABOUT US',
    lithree: 'GALLERY',
    lifour: 'SERVICES',
    Allrights: '© 2025 Kinzel Transporte.de. All rights reserved.',
    firstchoiceNav: 'HOME PAGE',
    secondchoice: 'ABOUT US',
    thirdchoice: 'GALLERY',
    fourthchoice: 'SERVICES'


    
  },

  ru: {
    startseite: 'Главная',
    ueberUns: 'О нас',
    galerie: 'Галерея',
    leistungen: 'Услуги',
    headline: 'Точность — наш движущий фактор\nДоверие — наша сила',
    mainQuestion: 'Что такое KINZEL TRANSPORTE.DE?',
    mainDescription: 'KINZEL TRANSPORTE — растущая транспортная компания из Эльмсхорна. В настоящее время наш автопарк насчитывает 25 контейнеровозов и находится недалеко от порта Гамбурга. Основанная в 2019 году г-ном Кинцелем, компания быстро превратилась в высокоэффективного поставщика транспортных и логистических услуг благодаря сплоченной команде. Наш автопарк позволяет нам максимально гибко подходить к потребностям клиентов и индивидуально подходить к каждому. Будь то сжатые сроки, доставка «точно в срок» или временное хранение — наш приоритет — удовлетворение ожиданий клиентов.',
    fleetTitle: 'Встречайте флот: Кинзель в пути',
    portTitle: 'Движущая сила порта Гамбурга',
    portText: 'Благодаря своему стратегическому расположению рядом с портом Гамбурга, компания Kinzel Transporte находится в самом центре немецкой логистики. Наши грузовики ежедневно обслуживают многочисленные терминалы и контейнерные склады, обеспечивая бесперебойную и быструю доставку грузов. Мы тесно сотрудничаем с местными операторами, портовыми властями и международными клиентами, гарантируя эффективную и пунктуальную доставку. Благодаря региональному опыту и надежным партнерским отношениям, Kinzel является предпочтительным партнером по контейнерным перевозкам в Гамбурге и его окрестностях.',
    locationTitle: 'Вот где вы нас найдете',
    locationDescription: 'Мы предлагаем морские контейнерные перевозки. Наши основные регионы деятельности — порты Гамбурга и Бремена. Маршруты наших водителей охватывают весь север Германии. Более крупные маршруты доставки возможны по запросу.',
    advert1: '✓ Идеальные поставки',
    advert2: '✓ Своевременные поставки',
    advert3: '✓ Надежные сборные перевозки',
    advert4: '✓ Безопасность грузов',
    workTitle: 'Какую рабочую среду мы предлагаем',
    workDescription: 'Мы обеспечиваем следующую деятельность, показанную на фотографиях ниже: современное оборудование, организованную логистику и стабильную рабочую среду, где важна каждая деталь.',
    image1: 'Тяжелые грузовики',
    image2: 'Работа в команде',
    image3: 'Масштаб и точность',
    copyright: '© 2025 Kinzel Transporte.de. Все права защищены.',
    headlinefirst: 'Точность — наша движущая сила. Доверие — наша сила.',
    headlineDescription: 'KINZEL TRANSPORTE.DE offers reliable and secure container transport with a modern fleet and proven service.',
    whatIsK: 'Что такое KINZEL TRANSPORTE.DE?',
    whatIsKDes: 'KINZEL TRANSPORTE — растущая транспортная компания из Эльмсхорна. В настоящее время наш автопарк насчитывает 25 контейнеровозов и находится недалеко от порта Гамбурга. Основанная в 2019 году г-ном Кинцелем, компания быстро превратилась в высокоэффективного поставщика транспортных и логистических услуг благодаря сплоченной команде. Наш автопарк позволяет нам максимально гибко подходить к потребностям клиентов и индивидуально подходить к каждому. Будь то сжатые сроки, доставка «точно в срок» или временное хранение — наш приоритет — удовлетворение ожиданий клиентов.',
    onMove: 'Знакомьтесь с флотом: Kinzel на ходу',
    nextToVideo: 'Движущая сила порта Гамбурга',
    NextToVideoPar: 'Благодаря своему стратегическому расположению в непосредственной близости от порта Гамбурга, компания Kinzel Transporte находится в самом центре немецкой логистики. Наши буксиры ежедневно обслуживают многочисленные терминалы и контейнерные склады, обеспечивая бесперебойную и быструю перевалку грузов из порта в порт. Мы тесно сотрудничаем с местными операторами, портовыми властями и международными клиентами, чтобы гарантировать эффективную и своевременную доставку каждого груза в пункт назначения. Благодаря нашему региональному опыту и налаженным партнерским отношениям, Kinzel Transporte зарекомендовала себя как надежный и предпочтительный партнер в сфере контейнерных перевозок в Гамбурге и его окрестностях.',
    locationTitle: 'Вы можете найти нас здесь', 
    locationTitleP: 'Мы предлагаем морские контейнерные перевозки. Наша основная зона деятельности — порты Гамбурга и Бремена. Наши туры с водителем выходят за пределы этих регионов и охватывают весь север Германии. Более продолжительные туры доступны по запросу.',
    first: 'Безупречные поставки',
    second: 'Своевременные поставки',
    third: 'Надежные сборные перевозки',
    fourth: 'Крепление груза',
    highlighthtwo: 'Какая у нас рабочая среда:',
    highlighthtwoP:'Мы предлагаем следующие виды деятельности, которые вы можете видеть на фотографиях ниже: современное оборудование, налаженная логистика и стабильная рабочая среда, где важна каждая деталь.',
    truck1text:'Большие Грузовики',
    truck2text:'Работа в команде',
    truck3text:'Масштаб и точность',
    lione: 'Главная',
    litwo: 'О нас',
    lithree: 'Галерея',
    lifour: 'Услуги',
    Allrights: '© 2025 Kinzel Transporte.de. Все права защищены.',
    firstchoiceNav: 'Главная',
    secondchoice: 'О нас',
    thirdchoice: 'Галерея',
    fourthchoice: 'Услуги'
  },

  tr: {
    startseite: 'Ana Sayfa',
    ueberUns: 'Hakkımızda',
    galerie: 'Galeri',
    leistungen: 'Hizmetler',
    headline: 'Hassasiyet bizim itici gücümüzdür\nGüven bizim gücümüzdür',
    mainQuestion: 'KINZEL TRANSPORTE.DE nedir?',
    mainDescription: 'KINZEL TRANSPORTE, Elmshorn merkezli büyüyen bir nakliye şirketidir. Filomuzda şu anda 25 konteyner şasi kamyon bulunmaktadır ve Hamburg Limanı yakınlarında bulunmaktadır. 2019 yılında Sayın Kinzel tarafından kurulan şirket, özverili ekibimiz sayesinde hızla yüksek performanslı bir nakliye ve lojistik hizmetleri sağlayıcısı haline gelmiştir. Filomuz, müşteri ihtiyaçlarına maksimum esneklik ve kişiselleştirilmiş yanıtlar sunmamızı sağlar. İster zaman baskısı, ister tam zamanında teslimat, ister geçici depolama olsun, önceliğimiz müşteri beklentilerini karşılamaktır.',
    fleetTitle: 'Filoyla Tanışın: Kinzel Yolda',
    portTitle: 'Hamburg Limanının İtici Gücü',
    portText: 'Kinzel Transporte, Hamburg Limanına yakın stratejik konumu sayesinde Alman lojistiğinin kalbinde faaliyet göstermektedir. Kamyonlarımız her gün çok sayıda terminal ve konteyner deposuna hizmet vererek sorunsuz ve hızlı kargo taşımacılığı sağlar. Yerel operatörler, liman yetkilileri ve uluslararası müşterilerle yakın iş birliği içinde çalışarak verimli ve zamanında teslimatlar sağlıyoruz. Bölgesel uzmanlığımız ve güvenilir ortaklıklarımızla Kinzel, Hamburg ve çevresinde konteyner taşımacılığında tercih edilen bir ortaktır.',
    locationTitle: 'Bizi Burada Bulabilirsiniz',
    locationDescription: 'Deniz konteyner taşımacılığı hizmeti sunuyoruz. Ana faaliyet alanlarımız Hamburg ve Bremen limanlarıdır. Sürücü rotalarımız Almanyanın tüm kuzey bölgesini kapsamaktadır. Talep üzerine daha geniş teslimat rotaları da mevcuttur.',
    advert1: '✓ Mükemmel Teslimatlar',
    advert2: '✓ Zamanında Teslimatlar',
    advert3: '✓ Güvenilir Grupaj Taşımacılığı',
    advert4: '✓ Kargo Güvenliği',
    workTitle: 'Ne Tür Bir Çalışma Ortamı Sunuyoruz',
    workDescription: 'Aşağıdaki fotoğraflarda görülen faaliyetlerimizi; modern ekipman, organize lojistik ve her detayın önemli olduğu istikrarlı bir çalışma ortamı ile sağlıyoruz.',
    image1: 'Ağır Hizmet Kamyonları',
    image2: 'Ekip çalışması',
    image3: 'Ölçek ve Hassasiyet',
    copyright: '© 2025 Kinzel Transporte.de. Her hakkı saklıdır.',
    headlinefirst: 'Hassasiyet itici gücümüzdür Güven gücümüzdür',
    headlineDescription: 'KINZEL TRANSPORTE.DE modern filosu ve kanıtlanmış hizmetiyle güvenilir ve emniyetli konteyner taşımacılığı sunmaktadır.',
    whatIsK: 'KINZEL TRANSPORTE.DE nedir?',
    whatIsKDes: 'KINZEL TRANSPORTE, Elmshorn merkezli büyüyen bir nakliye şirketidir. Filomuzda şu anda 25 konteyner şasi kamyon bulunmaktadır ve Hamburg Limanı yakınlarında bulunmaktadır. 2019 yılında Sayın Kinzel tarafından kurulan şirket, özverili ekibimiz sayesinde hızla yüksek performanslı bir nakliye ve lojistik hizmetleri sağlayıcısı haline gelmiştir. Filomuz, müşteri ihtiyaçlarına maksimum esneklik ve kişiselleştirilmiş yanıtlar sunmamızı sağlar. İster zaman baskısı, ister tam zamanında teslimat, ister geçici depolama olsun, önceliğimiz müşteri beklentilerini karşılamaktır.',
    onMove: 'Filoyla Tanışın: Kinzel Yolda',
    nextToVideo: 'Hamburg Limanının İtici Gücü',
    NextToVideoPar: 'Kinzel Transporte, Hamburg Limanına yakın stratejik konumu sayesinde Alman lojistiğinin kalbinde faaliyet göstermektedir. Kamyonlarımız her gün çok sayıda terminal ve konteyner deposuna hizmet vererek sorunsuz ve hızlı kargo taşımacılığı sağlar. Yerel operatörler, liman yetkilileri ve uluslararası müşterilerle yakın iş birliği içinde çalışarak verimli ve zamanında teslimatlar sağlıyoruz. Bölgesel uzmanlığımız ve güvenilir ortaklıklarımızla Kinzel, Hamburg ve çevresinde konteyner taşımacılığında tercih edilen bir ortaktır.',
    locationTitle: 'Bizi burada bulabilirsiniz', 
    locationTitleP: 'Deniz konteyner taşımacılığı hizmeti sunuyoruz. Ana faaliyet alanımız Hamburg ve Bremen limanlarıdır. Şoförlü turlarımız bu bölgelerin ötesine uzanarak tüm Kuzey Almanya bölgesini kapsamaktadır. Talep üzerine daha uzun turlar da mevcuttur.',
    first: 'Kusursuz teslimatlar',
    second: 'Zamanında Teslimatlar',
    third: 'Güvenilir Grupaj Taşımacılığı',
    fourth: 'Yük emniyeti',
    highlighthtwo: 'Nasıl bir çalışma ortamımız var:',
    highlighthtwoP:'Aşağıdaki fotoğraflarda görebileceğiniz faaliyetlerimizi; modern ekipmanlar, organize lojistik ve her detayın önemli olduğu istikrarlı bir çalışma ortamıyla sunuyoruz.',
    truck1text:'Büyük Kamyonlar',
    truck2text:'Takım çalışması',
    truck3text:'Ölçek ve Hassasiyet',
    lione: 'Ana Sayfa',
    litwo: 'Hakkımızda',
    lithree: 'Galeri',
    lifour: 'Hizmetler',
    Allrights: '© 2025 Kinzel Transporte.de. Her hakkı saklıdır.',
    firstchoiceNav: 'Ana Sayfa',
    secondchoice: 'Hakkımızda',
    thirdchoice: 'Galeri',
    fourthchoice: 'Hizmetler'
  }
}




